apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasher
    application: dockercoins
  name: hasher
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hasher
