apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    application: dockercoins
  name: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
