apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dockercoins
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: {{ .Values.ingress.host}}
    http:
      paths:
      - path: /
        backend:
          serviceName: webui
          servicePort: 80
