apiVersion: v1
kind: Service
metadata:
  labels:
    app: webui
    version: v1
    application: dockercoins
  name: webui
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000
  selector:
    app: webui
    application: dockercoins
  type: NodePort
status:
  loadBalancer: {}
