apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: chevereto
  name: chevereto
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32100
  selector:
    io.kompose.service: chevereto
status:
  loadBalancer: {}
