apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: memleak
  name: memleak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memleak
  strategy: {}
  template:
    metadata:
      labels:
        app: memleak
    spec:
      containers:
      - image: jerem44/memory-leak-app:scratch
        name: memory-leak-app
        resources: 
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

