apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
 name: nginx
 annotations:
   ingress.kubernetes.io/ssl-redirect: "false"
   traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
 rules:
 - host: 172.18.0.5.nip.io
   http:
     paths:
     - path: /nginx
       backend:
         serviceName: nginx
         servicePort: 80