apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

images:
  - name: jerem44/hasher
    newTag: dev
  - name: jerem44/rng
    newTag: dev
  - name: jerem44/worker
    newTag: dev
  - name: jerem44/webui
    newTag: dev

patches:
  - ingress_patch.yaml