apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rng
    application: dockercoins
    toto: test
  name: rng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rng
      application: dockercoins
  strategy: {}
  template:
    metadata:
      labels:
        app: rng
        application: dockercoins
    spec:
      containers:
      - image: dockercoins/rng:v0.1
        name: rng
        resources: {}
status: {}
