apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webui
    version: beta
    application: dockercoins
  name: webui-betea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
      version: beta
  strategy: {}
  template:
    metadata:
      labels:
        app: webui
        application: dockercoins
        version: beta
    spec:
      containers:
      - image: dockercoins/webui:v0.2
        name: webui
        resources: {}
status: {}
