apiVersion: v1
kind: Service
metadata:
  labels:
    app: chevereto
  name: chevereto
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: {{ .Values.nodePort }}
  selector:
    app: chevereto

